-- Phase 2 

-- Creating Dim_Customer table
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID STRING PRIMARY KEY,
    CUSTOMER_EMAIL STRING,
    PHONE STRING,
    REGION_ID STRING,
    Connection_Type String
);

-- Creating DIM_REGION Table
CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID STRING PRIMARY KEY,
    ZONE STRING,
    COUNTRY STRING,
    STATE STRING,
    BRANCH STRING
);

-- Creating DIM_WEATHER Table
CREATE OR REPLACE TABLE DIM_WEATHER (
    WEATHER_KEY INTEGER AUTOINCREMENT START 1,
    REGION_ID STRING PRIMARY KEY,
    WEATHER_DATE TIMESTAMP,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    WIND_SPEED FLOAT,
    SOLAR_INDEX FLOAT
);


-- Creating FACT_CONSUMPTION Table
CREATE OR REPLACE TABLE FACT_CONSUMPTION (
    CONSUMPTION_KEY INTEGER AUTOINCREMENT START 1 PRIMARY KEY,
    CUSTOMER_ID STRING,
    REGION_ID STRING,
    TIMESTAMP TIMESTAMP,
    CONSUMPTION_KWH FLOAT,
    AVERAGE_KW FLOAT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID),
    FOREIGN KEY (REGION_ID) REFERENCES DIM_WEATHER(REGION_ID)
);

-- Creating FACT_LOAD Table
CREATE OR REPLACE TABLE FACT_LOAD (
    LOAD_KEY INTEGER AUTOINCREMENT START 1 PRIMARY KEY,
    REGION_ID STRING,
    TIMESTAMP TIMESTAMP,
    LOAD_MW FLOAT,
    UTILIZATION_PCT FLOAT,
    TRANSFORMER_COUNT INTEGER,
    LOSSES_PCT FLOAT,
    FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID)
);

-- Creating FACT_GENERATION Table
CREATE OR REPLACE TABLE FACT_GENERATION (
    GENERATION_KEY INTEGER AUTOINCREMENT START 1 PRIMARY KEY,
    REGION_ID STRING,
    GenDate DATE,
    SOURCE STRING,
    GENERATED_MWH FLOAT,
    INSTALLED_CAPACITY_MW FLOAT,
    CAPACITY_FACTOR_PCT FLOAT,
    FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID)
);

//Inserting data into dimension and fact tables

-- Inserting data into DIM_CUSTOMER
MERGE INTO DIM_CUSTOMER AS TARGET
USING CUSTOMER_PROFILE AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMERID
WHEN MATCHED THEN UPDATE SET
    TARGET.CUSTOMER_EMAIL = SOURCE.EMAIL,
    TARGET.PHONE = SOURCE.PHONE,
    TARGET.REGION_ID = SOURCE.REGIONID,
    TARGET.Connection_Type = SOURCE.ConnectionType
WHEN NOT MATCHED THEN
INSERT (CUSTOMER_ID, CUSTOMER_EMAIL, PHONE, REGION_ID, Connection_Type)
VALUES (SOURCE.CUSTOMERID, SOURCE.EMAIL, SOURCE.PHONE, SOURCE.REGIONID, SOURCE.CONNECTIONTYPE);

select * from dim_customer;

-- Inserting data into DIM_REGION
MERGE INTO DIM_REGION AS TARGET
USING REGION_HIERARCHY AS SOURCE
ON TARGET.REGION_ID = SOURCE.REGIONID
WHEN MATCHED THEN UPDATE SET
    TARGET.ZONE = SOURCE.ZONE,
    TARGET.COUNTRY = SOURCE.COUNTRY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.BRANCH = SOURCE.BRANCH
WHEN NOT MATCHED THEN
INSERT (REGION_ID, ZONE, COUNTRY, STATE, BRANCH)
VALUES (SOURCE.REGIONID, SOURCE.ZONE, SOURCE.COUNTRY, SOURCE.STATE, SOURCE.BRANCH);

select * from dim_region;

-- Inserting data into DIM_WEATHER
MERGE INTO DIM_WEATHER AS TARGET
USING WEATHER_DATA AS SOURCE
ON TARGET.REGION_ID = SOURCE.REGIONID AND TARGET.WEATHER_DATE = SOURCE.WEATHERDATE
WHEN MATCHED THEN UPDATE SET
    TARGET.TEMPERATURE = SOURCE.TEMPERATUREC,
    TARGET.HUMIDITY = SOURCE.HUMIDITYPCT,
    TARGET.WIND_SPEED = SOURCE.WINDSPEEDKMPH,
    TARGET.SOLAR_INDEX = SOURCE.SOLARIRRADIANCE
WHEN NOT MATCHED THEN
INSERT (REGION_ID, WEATHER_DATE, TEMPERATURE, HUMIDITY, WIND_SPEED, SOLAR_INDEX)
VALUES (SOURCE.REGIONID, SOURCE.WEATHERDATE, SOURCE.TEMPERATUREC, SOURCE.HUMIDITYPCT, SOURCE.WINDSPEEDKMPH, SOURCE.SOLARIRRADIANCE);

select * from dim_weather;

--dim_date table
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY            DATE PRIMARY KEY,
    YEAR                NUMBER(4,0),
    MONTH_NUM           NUMBER(2,0),
    MONTH_NAME          STRING,
    QUARTER             NUMBER(1,0),
    WEEK_OF_YEAR        NUMBER(2,0),
    DAY_OF_MONTH        NUMBER(2,0),
    DAY_OF_WEEK_NUM     NUMBER(1,0),
    DAY_NAME            STRING,
    DAY_TYPE            STRING,   
    FIRST_DAY_OF_MONTH  DATE,
    LAST_DAY_OF_MONTH   DATE
);


INSERT INTO DIM_DATE (
    DATE_KEY,
    YEAR,
    MONTH_NUM,
    MONTH_NAME,
    QUARTER,
    WEEK_OF_YEAR,
    DAY_OF_MONTH,
    DAY_OF_WEEK_NUM,
    DAY_NAME,
    DAY_TYPE,
    FIRST_DAY_OF_MONTH,
    LAST_DAY_OF_MONTH
)
WITH dates AS (
    SELECT
        DATEADD(day, SEQ4(), '2021-01-01') AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 2192))
    WHERE DATEADD(day, SEQ4(), '2022-01-01') <= '2025-12-31'
)
SELECT
    DATE_VALUE AS DATE_KEY,
    YEAR(DATE_VALUE),
    MONTH(DATE_VALUE),
    MONTHNAME(DATE_VALUE),
    QUARTER(DATE_VALUE),
    WEEKOFYEAR(DATE_VALUE),
    DAY(DATE_VALUE),
    DAYOFWEEK(DATE_VALUE),
    DAYNAME(DATE_VALUE),
    CASE WHEN DAYOFWEEK(DATE_VALUE) IN (1, 7) THEN 'Weekend' ELSE 'Weekday' END,
    DATE_TRUNC('month', DATE_VALUE),
    LAST_DAY(DATE_VALUE)
FROM dates;

select * from dim_date;

ALTER TABLE FACT_CONSUMPTION ADD COLUMN DATE_KEY DATE;
ALTER TABLE FACT_LOAD ADD COLUMN DATE_KEY DATE;
ALTER TABLE FACT_GENERATION ADD COLUMN DATE_KEY DATE;

UPDATE FACT_CONSUMPTION
SET DATE_KEY = DATE(TIMESTAMP);

UPDATE FACT_LOAD
SET DATE_KEY = DATE(TIMESTAMP);

UPDATE FACT_GENERATION
SET DATE_KEY = GenDate;   

ALTER TABLE FACT_CONSUMPTION
ADD CONSTRAINT FK_CONSUMPTION_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);

ALTER TABLE FACT_LOAD
ADD CONSTRAINT FK_LOAD_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);

ALTER TABLE FACT_GENERATION
ADD CONSTRAINT FK_GENERATION_DATE
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);

delete from dim_Date where year = 2026 or year = 2021;


-- Inserting data into FACT_CONSUMPTION
MERGE INTO FACT_CONSUMPTION AS TARGET
USING SMARTMETER_READINGS AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMERID AND TARGET.TIMESTAMP = SOURCE.TIMESTAMP
WHEN MATCHED THEN UPDATE SET
    TARGET.CONSUMPTION_KWH = SOURCE.KWH,
    TARGET.AVERAGE_KW = SOURCE.AVGKW
WHEN NOT MATCHED THEN
INSERT (CUSTOMER_ID, REGION_ID, TIMESTAMP, CONSUMPTION_KWH, AVERAGE_KW)
VALUES (SOURCE.CUSTOMERID, SOURCE.REGIONID, SOURCE.TIMESTAMP, SOURCE.KWH, SOURCE.AVGKW);

MERGE INTO FACT_CONSUMPTION AS TARGET
USING (
    SELECT DISTINCT
        S.CUSTOMERID,
        S.REGIONID,
        S.TIMESTAMP,
        S.KWH,
        S.AVGKW,
        DC.CUSTOMER_ID AS DIM_CUSTOMER_ID,
        DR.REGION_ID AS DIM_REGION_ID,
        DW.REGION_ID AS DIM_WEATHER_REGION_ID
    FROM SMARTMETER_READINGS AS S
    LEFT JOIN DIM_CUSTOMER AS DC 
        ON S.CUSTOMERID = DC.CUSTOMER_ID
    LEFT JOIN DIM_REGION AS DR 
        ON S.REGIONID = DR.REGION_ID
    LEFT JOIN DIM_WEATHER AS DW 
        ON S.TIMESTAMP = DW.WEATHER_DATE 
       AND S.REGIONID = DW.REGION_ID
) AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMERID 
   AND TARGET.TIMESTAMP = SOURCE.TIMESTAMP
WHEN MATCHED THEN 
    UPDATE SET 
        TARGET.CONSUMPTION_KWH = SOURCE.KWH,
        TARGET.AVERAGE_KW = SOURCE.AVGKW
WHEN NOT MATCHED THEN 
    INSERT (CUSTOMER_ID, REGION_ID, TIMESTAMP, CONSUMPTION_KWH, AVERAGE_KW)
    VALUES (SOURCE.CUSTOMERID, SOURCE.REGIONID, SOURCE.TIMESTAMP, SOURCE.KWH, SOURCE.AVGKW);

select * from fact_consumption;


-- Inserting data into FACT_LOAD
MERGE INTO FACT_LOAD AS TARGET
USING STG_SUBSTATION_LOAD AS SOURCE
ON TARGET.REGION_ID = SOURCE.REGIONID AND TARGET.TIMESTAMP = SOURCE.TIMESTAMP
WHEN MATCHED THEN UPDATE SET
    TARGET.LOAD_MW = SOURCE.LOADMW,
    TARGET.UTILIZATION_PCT = SOURCE.UTILIZATIONPCT,
    TARGET.TRANSFORMER_COUNT = SOURCE.TRANSFORMERCOUNT,
    TARGET.LOSSES_PCT = SOURCE.LOSSESPCT
WHEN NOT MATCHED THEN
INSERT (REGION_ID, TIMESTAMP, LOAD_MW, UTILIZATION_PCT, TRANSFORMER_COUNT, LOSSES_PCT)
VALUES (SOURCE.REGIONID, SOURCE.TIMESTAMP, SOURCE.LOADMW, SOURCE.UTILIZATIONPCT, SOURCE.TRANSFORMERCOUNT, SOURCE.LOSSESPCT);

select * from fact_load;
select sum(LOAD_MW) from fact_load;

-- Inserting data into FACT_GENERATION
MERGE INTO FACT_GENERATION AS TARGET
USING RENEWABLE_GENERATION AS SOURCE
ON TARGET.REGION_ID = SOURCE.REGIONID AND TARGET.GenDate = SOURCE.GenDate
WHEN MATCHED THEN UPDATE SET
    TARGET.GENERATED_MWH = SOURCE.GENERATEDMWH,
    TARGET.INSTALLED_CAPACITY_MW = SOURCE.INSTALLEDCAPACITYMW,
    TARGET.CAPACITY_FACTOR_PCT = SOURCE.CAPACITYFACTORPCT
WHEN NOT MATCHED THEN
INSERT (REGION_ID, GenDate, SOURCE, GENERATED_MWH, INSTALLED_CAPACITY_MW, CAPACITY_FACTOR_PCT)
VALUES (SOURCE.REGIONID, SOURCE.GenDate, SOURCE.SOURCE, SOURCE.GENERATEDMWH, SOURCE.INSTALLEDCAPACITYMW, SOURCE.CAPACITYFACTORPCT);

select * from fact_generation;



