-- PHASE 4

create or replace role full_access;
create or replace role half_access;

--masking policy
CREATE OR REPLACE MASKING POLICY MP_EMAIL
AS (val STRING) RETURNS STRING ->
CASE 
    WHEN CURRENT_ROLE() IN ('FULL_ACCESS','ACCOUNTADMIN') THEN val
    ELSE CONCAT('XXXXXX', RIGHT(val, 4))
END;

CREATE OR REPLACE MASKING POLICY MP_PHONE
AS (val STRING) RETURNS STRING ->
CASE 
    WHEN CURRENT_ROLE() IN ('FULL_ACCESS','ACCOUNTADMIN') THEN val
    ELSE CONCAT('XXXXXX', RIGHT(val, 3))  
END;

ALTER TABLE DIM_CUSTOMER 
MODIFY COLUMN CUSTOMER_EMAIL 
SET MASKING POLICY MP_EMAIL;

ALTER TABLE DIM_CUSTOMER 
MODIFY COLUMN PHONE 
SET MASKING POLICY MP_PHONE;

grant role full_access to user ayushyadav777;
USE ROLE full_access;
select * from dim_customer;

grant role half_access to user ayushyadav777;
use role half_access;
select * from dim_customer;

create or replace table fact_consumption_new as
(select consumption_key, customer_id, fc.region_id, timestamp, consumption_kwh, average_kw, country from fact_consumption fc join
region_hierarchy rh on
fc.region_id = rh.regionid);

CREATE or replace ROLE AUSTRALIA_ROLE;
CREATE or replace ROLE CANADA_ROLE;
CREATE or replace ROLE FRANCE_ROLE;
CREATE or replace ROLE GERMANY_ROLE;
CREATE or replace ROLE INDIA_ROLE;
CREATE or replace ROLE UK_ROLE;
CREATE or replace ROLE USA_ROLE;

GRANT ROLE australia_role TO USER ayushyadav777;
grant role usa_role to user ayushyadav777;
GRANT ROLE canada_role TO USER ayushyadav777;
GRANT ROLE france_role TO USER ayushyadav777;
GRANT ROLE germany_role TO USER ayushyadav777;
GRANT ROLE india_role TO USER ayushyadav777;
GRANT ROLE uk_role TO USER ayushyadav777;

GRANT SELECT ON TABLE FACT_CONSUMPTION_NEW TO ROLE AUSTRALIA_ROLE;

CREATE OR REPLACE ROW ACCESS POLICY country_role_based_policy
AS (country STRING)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'FULL_ACCESS_ROLE', 'DATA_ADMIN') THEN TRUE
        WHEN CURRENT_ROLE() = 'AUSTRALIA_ROLE' AND country = 'Australia' THEN TRUE
        WHEN CURRENT_ROLE() = 'CANADA_ROLE'     AND country = 'Canada' THEN TRUE
        WHEN CURRENT_ROLE() = 'FRANCE_ROLE'     AND country = 'France' THEN TRUE
        WHEN CURRENT_ROLE() = 'GERMANY_ROLE'    AND country = 'Germany' THEN TRUE
        WHEN CURRENT_ROLE() = 'INDIA_ROLE'      AND country = 'India' THEN TRUE
        WHEN CURRENT_ROLE() = 'UK_ROLE'         AND country = 'UK' THEN TRUE
        WHEN CURRENT_ROLE() = 'USA_ROLE'        AND country = 'USA' THEN TRUE
        ELSE FALSE
    END;

select * from FACT_CONSUMPTION_NEW;

ALTER TABLE FACT_CONSUMPTION_NEW
ADD ROW ACCESS POLICY country_role_based_policy
ON (COUNTRY);

-- Loop grants for all roles
GRANT USAGE ON DATABASE ALL_FILES TO ROLE AUSTRALIA_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE BRAZIL_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE CANADA_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE CHINA_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE FRANCE_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE GERMANY_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE INDIA_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE UK_ROLE;
GRANT USAGE ON DATABASE ALL_FILES TO ROLE USA_ROLE;

GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE AUSTRALIA_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE BRAZIL_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE CANADA_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE CHINA_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE FRANCE_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE GERMANY_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE INDIA_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE UK_ROLE;
GRANT USAGE ON SCHEMA ALL_FILES.CAPSTONE_SCHEMA TO ROLE USA_ROLE;

GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE AUSTRALIA_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE BRAZIL_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE CANADA_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE CHINA_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE FRANCE_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE GERMANY_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE INDIA_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE UK_ROLE;
GRANT SELECT ON TABLE ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW TO ROLE USA_ROLE;

USE ROLE ACCOUNTADMIN;
USE ROLE INDIA_ROLE;
SELECT DISTINCT * FROM ALL_FILES.CAPSTONE_SCHEMA.FACT_CONSUMPTION_NEW;


-- task 12 - data sharing
CREATE OR REPLACE SHARE secure_energy_share;

GRANT USAGE ON DATABASE ALL_FILES TO SHARE secure_energy_share;
GRANT USAGE ON SCHEMA CAPSTONE_SCHEMA TO SHARE secure_energy_share;

CREATE MANAGED ACCOUNT reader_acc
ADMIN_NAME = reader_admin
ADMIN_PASSWORD = 'StrongPassword123'
type = reader;

ALTER SHARE secure_energy_share ADD ACCOUNTS = QHYZUSA.READER_ACC;

select * from mv_load_forecast_accuracy;
select * from mv_overload_watchlist;

CREATE OR REPLACE SECURE VIEW shared_energy_metrics AS
SELECT
    a.REGION_ID,
    a.total_consumption_kwh,
    b.LOAD_MW,
    b.UTILIZATION_PCT,
    b.TRANSFORMER_COUNT
FROM mv_load_forecast_accuracy a
LEFT JOIN mv_overload_watchlist b
    ON a.REGION_ID = b.REGION_ID;

GRANT SELECT ON view all_files.capstone_schema.shared_energy_metrics TO SHARE secure_energy_share;

show managed accounts;
